name: Build and Release APK

on:
  push:
    tags:
      - 'v*'  # バージョンタグを push したときに実行

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest

    steps:
      # 1. リポジトリをチェックアウト
      - name: Checkout repo
        uses: actions/checkout@v3

      # 2. Java & Android 環境セットアップ
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 11

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2
        with:
          api-level: 33
          build-tools-version: 33.0.2

      # 3. Gradle Wrapper を使って APK ビルド
      - name: Build APK
        run: ./gradlew assembleRelease

      # 4. GitHub Release に APK をアップロード
      - name: Create Release
        id: create_release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ github.ref_name }}  # push したタグ名を使用
          artifacts: app/build/outputs/apk/release/app-release.apk
          overwrite: true
