name: Manual Debug Release

on:
  workflow_dispatch:
    inputs:
      release_type:
        description: "Release type (patch/minor/major)"
        required: true
        default: "patch"

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Build Debug APK
        run: ./gradlew assembleDebug

      - name: Get next version
        id: version
        run: |
          # 最新タグ取得
          latest_tag=$(git tag --list 'v*' | sort -V | tail -n1)
          latest_tag=${latest_tag:-v0.0.0}

          IFS='.' read -r major minor patch <<<"${latest_tag#v}"

          case "${{ github.event.inputs.release_type }}" in
            patch) patch=$((patch + 1)) ;;
            minor) minor=$((minor + 1)); patch=0 ;;
            major) major=$((major + 1)); minor=0; patch=0 ;;
          esac

          new_tag="v$major.$minor.$patch"

          # 既に同じタグが存在するか確認
          if git rev-parse "$new_tag" >/dev/null 2>&1; then
            echo "Tag $new_tag already exists. Skipping release."
            echo "skip_release=true" >> $GITHUB_OUTPUT
          else
            echo "skip_release=false" >> $GITHUB_OUTPUT
            echo "new_tag=$new_tag" >> $GITHUB_OUTPUT
          fi

      - name: Create and push tag
        if: steps.version.outputs.skip_release == 'false'
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git tag ${{ steps.version.outputs.new_tag }}
          git push origin ${{ steps.version.outputs.new_tag }}

      - name: Create GitHub Release
        if: steps.version.outputs.skip_release == 'false'
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.version.outputs.new_tag }}
          name: "Debug APK ${{ steps.version.outputs.new_tag }}"
          body: "Debug build of the app."
          files: app/build/outputs/apk/debug/app-debug.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
